server:
  port: 8084
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: student
          uri: lb://STUDENT
          predicates:
            - Path=/student/**
        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/payment/**
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8083/eureka